name: Nginx Static Deploy
 
on:

  push:

    branches: [main]
 
jobs:

  deploy:

    runs-on: ubuntu-latest
 
    steps:

    - name: Checkout code

      uses: actions/checkout@v3
     
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
    
    - name: Build and Push Multi-Platform Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/hesapmakinesi:latest \
          --push \
          .

 
    - name: Deploy to VPS via SSH

      uses: appleboy/ssh-action@v1.0.0

      with:

        host: ${{ secrets.VPS_HOST }}

        username: ${{ secrets.VPS_USER }}

        key: ${{ secrets.VPS_SSH_KEY }}

        script: |

          docker pull ${{ secrets.DOCKER_USERNAME }}/hesapmakinesi:latest

          docker stop mynginx || true

          docker rm mynginx || true

          docker run -d --name mynginx -p 80:80 ${{ secrets.DOCKER_USERNAME }}/hesapmakinesi:latest
 
